#CI项目
name: WRT-TEST

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      TARGET:
        default: 'rockchip'
        required: true
        type: choice
        options: [x86_64, rockchip, qualcommax, mediatek]
      SUBTARGET:
        default: 'generic'
        required: true
        type: choice
        options: [ipq60xx, ipq807x, mt7981, mt7986,generic]
      REPO:
        default: 'immortalwrt/immortalwrt'
        required: true
        type: choice
        options: 
            - 'immortalwrt/immortalwrt'
            - 'VIKINGYFY/immortalwrt'
            - 'hanwckf/immortalwrt-mt798x'
            - 'padavanonly/immortalwrt-mt798x'
      BRANCH:
        default: 'master'
        required: true
        type: choice
        options: 
            - 'master'
            - 'main'
            - 'openwrt-21.02'
      PACKAGE:
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'true'
        required: true
        type: string

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.TARGET}}
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{inputs.TARGET}}
      #固件子平台
      WRT_SUBTARGET: ${{inputs.SUBTARGET}}
       #固件架构（用于预置插件内核下载）
      WRT_ARCH: 'unknown'
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: ImmortalWrt
      #默认WIFI名称
      WRT_SSID: ImmortalWrt
      #默认WIFI密码
      WRT_WORD: immortalwrt
      #默认地址
      WRT_IP: 192.168.6.1
      #源码
      WRT_REPO: ${{inputs.REPO}}
      #分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
